### ISSUE TITLE
DCRNN example does not run

### ISSUE THREAD

**Issue by klane** [Rose-STL-Lab/torchTS#40]
The `DCRNN` constructor accepts `num_units` as the second positional argument, not as a keyword argument. The way the example is written below, the scalar is passed in as the number of units.

https://github.com/Rose-STL-Lab/torchTS/blob/225d44538c0f43a7cb5bc48e05fff2fcebc2a466/examples/dcrnn/main.py#L44

**Comment by akashshah59** [comment]
Bug fixed, the code was designed to run for earlier versions of torchTS, in which there was need for a scalar.

**Comment by klane** [comment]
Verified example runs now.
