### ISSUE TITLE
Permit sparse matrices in Laplacian filter

### ISSUE THREAD

**Issue by klane** [Rose-STL-Lab/torchTS#49]
The line to enforce symmetry does not support sparse matrices. A potential fix is either to convert to dense and back to sparse or raise an exception if the user selects the Laplacian filter with a sparse adjacency matrix.

https://github.com/Rose-STL-Lab/torchTS/blob/600b8c3263d503b5e397845b815fda77218461e7/torchts/utils/graph.py#L34

**Comment by akashshah59** [comment]
@klane There is an unusual `L.astype('float32')` present at the end of the scaled laplacian. 
I have often faced errors when my adjacency matrix type is float64 and I attribute it to this enforcement. Do you see a reason to keep this typecast?

**Comment by klane** [comment]
> @klane There is an unusual `L.astype('float32')` present at the end of the scaled laplacian.
> I have often faced errors when my adjacency matrix type is float64 and I attribute it to this enforcement. Do you see a reason to keep this typecast?

Good catch @akashshah59. This should probably be removed.
